on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get API Key
      id: api_key
      run: echo "::set-env name=API_KEY::${{ secrets.API_KEY }}"

    - name: Export API Key
      run: echo "API_KEY=${{ env.API_KEY }}"
      env:
        API_KEY: ${{ steps.api_key.outputs.API_KEY }}
