name: Export API Key

on: [push]

env:
  API_KEY: ${{ secrets.API_KEY }}

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
    - name: Export API Key
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: echo "API Key: $API_KEY"
